### PR TITLE
add threshold setting

### LINKED ISSUE #83: move threshold
There should be a threshold setting to allow scrolling only when the mouse or finger moves so far

### PR DESCRIPTION
**Pull request by UziTech**
Add threshold setting to move only if mouse moves farther than
threshold. Threshold setting can be a function.
fixes #83

### CODE REVIEW

**Comment by davetayls** [comment]
Hi, a couple of thoughts on this. 

I'd prefer the threshold to work by keeping track of Start position and measuring against that at each step I think.

Also, I know that sqrt isn't a particularly fast calculation. Whilst it's definitely more accurate it would be interesting to try and see if the experience works as well by just checking Y distance or X distance is greater than threshold relative to start position.

Let me know your thoughts

**Comment by davetayls** [comment]
Alternatively if just counting down the threshold works better the property should probably be `moveThresholdRemaining`

**Comment by davetayls** [comment]
Please can you also update the read me and include a test with the threshold setting. Cheers

**Comment by davetayls** [comment]
Just add the test to the end of https://github.com/davetayls/jquery.kinetic/blob/master/test/specs/basic.spec.js 👌

**Comment by UziTech** [comment]
https://jsperf.com/sqrt-vs-abs

I don't think Math.sqrt will affect the performance especially since it is being used before the scrolling occurs .

I agree it should be from starting position. I will fix that and create the tests.

**Comment by UziTech** [comment]
Not sure why the build fails. The tests pass when viewing them in any browser.
https://rawgit.com/UziTech/jquery.kinetic/master/test/specs/basic.html

**Comment by davetayls** [comment]
I'll take a look later this morning

**Comment by davetayls** [comment]
Just had a quick look on my phone and they aren't passing, is this because of the changes you have made to how the threshold works?

**Comment by UziTech** [comment]
found the bug in the dragOver() function the touch move event was moving to x,x instead of x,y and the threshold wasn't being crossed

**Comment by davetayls** [comment]
thanks @UziTech nice work, i'll merge this in and do a release :+1:

**Pull request merged**
