### PR TITLE
Added main property to package.json so package builders can work

### PR DESCRIPTION
**Pull request by michaelsouellette**
Added main property to package.json so package builders can grab the needed javascript file when compiling.

### CODE REVIEW

**Comment by davetayls** [comment]
Sure can you use the non minified version.

**Comment by michaelsouellette** [comment]
Done

**Comment by davetayls** [comment]
Great, I'll publish it this eve

**Comment by davetayls** [comment]
@michaelsouellette  I've published the new version to npm

**Comment by michaelsouellette** [comment]
Thanks!

**Pull request merged**
